# Generated by Django 2.1 on 2019-08-12 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0002_categoria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='limite_categoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
