# Generated by Django 2.1 on 2019-08-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0004_auto_20190812_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='esta_pago',
        ),
    ]
