# Generated by Django 2.1 on 2019-08-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0005_remove_gasto_esta_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='data_da_compra',
            new_name='data',
        ),
    ]
