# Generated by Django 2.1 on 2019-08-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0006_auto_20190812_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
    ]
