# Generated by Django 2.1 on 2019-08-14 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economiza', '0007_remove_categoria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
