# Generated by Django 2.1 on 2019-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0008_categoria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
