# Generated by Django 2.1 on 2019-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0010_remove_gasto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='data_do_gasto',
            field=models.DateField(null=True),
        ),
    ]
